---
- hosts: php
  vars_files:
    - vars.yml
  sudo: yes

  tasks:
   - name: uninstall packages
     apt: name={{ item }} update_cache=yes state=absent
     with_items: "{{ system_packages }}"
  
   - name: Delete code folders
     file: path='var/www/softdeplevo' state=absent

  handlers:
   - name: restart php7.0-fpm
     service: name=php7.0-fpm state=restarted

   - name: restart nginx
     service: name=nginx state=restarted
